import { FooterBanner, HeroBanner, Product } from "@/components";

import Head from "next/head";
import { client } from "@/lib/client";

export default function Home({ products, bannerData }) {
  return (
    <>
      <Head>
        <title>Willcommerce - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroBanner bannerData={bannerData.length && bannerData[0]} />

      <div className="products-heading">
        <h2>Best Selling products</h2>
        <p>Speakers of many variations</p>
      </div>

      <div className="products-container">
        {products.map((product, idx) => (
          <Product key={product._id} product={product} />
        ))}
      </div>

      <FooterBanner bannerData={bannerData[0]} />
    </>
  );
}

export const getServerSideProps = async () => {
  const query = '*[_type == "product"]';
  const products = await client.fetch(query);

  const bannerQuery = '*[_type == "banner"]';
  const bannerData = await client.fetch(bannerQuery);

  return {
    props: { products, bannerData },
  };
};
